In [153]:
import pandas as pd

In [152]:
import numpy as np

In [2]:
a1 = np.array([1, 2, 3])

In [3]:
a1.shape

(3,)

In [139]:
a2 = np.random.randint(0, 200, size=(100))

In [140]:
a2

array([ 26, 188, 139,  83,  28, 165,   8,  48, 140, 148,  48, 184, 187,
       104, 118,  18, 160, 174,  47, 125,   6, 166, 172,  94,  16,  96,
        49, 172,  37,  50,  60, 115,  55,  36,  40,  12,  16, 165,  30,
        41,  24, 163, 186,  44, 103,  89,  91,  56, 108,  23,   9, 183,
        58, 170, 126, 128,  71, 193, 101,  38,  58,  24, 172,  59,  77,
       193,  74, 155,  23,  27,  31, 109, 137,  57,  22, 127,  80, 162,
       129, 170,  39, 169, 123,  38,   5,  87, 172,  37, 193, 125, 151,
        55, 102,  91, 138,   6,  68,  61, 199,  15])

In [146]:
%%timeit
sum(a2)

15.5 µs ± 426 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [147]:
%%timeit
np.sum(a2)

4.16 µs ± 24.6 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [148]:
m1 = np.random.randint(0, 11, size=(3, 2))
m2 = np.random.randint(0, 11, size=(2, 3))

In [150]:
m3 = np.dot(m1, m2)
m3

array([[ 43, 120,  76],
       [ 50,  80,  40],
       [ 12,  32,  20]])

### Creating Nut Butter Example

In [151]:
butters = np.random.randint(0, 21, size=(5, 3))
butters

array([[ 5, 16,  1],
       [ 5,  1,  6],
       [ 3, 16,  7],
       [ 9,  8,  1],
       [ 9, 11, 10]])

In [242]:
df_butters = pd.DataFrame(
    data=butters, 
    columns=['Almond', 'Peanut', 'Cashew'], 
    index=['Mon', 'Tues', 'Wed', 'Thurs', 'Fri']
)
df_butters

Almond  Peanut  Cashew
Mon         5      16       1
Tues        5       1       6
Wed         3      16       7
Thurs       9       8       1
Fri         9      11      10

In [161]:
prices = np.random.randint(5, 16, size=(1, 3))
prices

array([[10, 11,  5]])

In [162]:
np.shape(prices)

(1, 3)

In [167]:
df_prices = pd.DataFrame(
    data=prices,
    columns=['Almond', 'Peanut', 'Cashew'],
    index=['Price']
)
df_prices

Almond  Peanut  Cashew
Price      10      11       5

In [219]:
df_butters

Almond  Peanut  Cashew
Mon         5      16       1
Tues        5       1       6
Wed         3      16       7
Thurs       9       8       1
Fri         9      11      10

In [174]:
df_prices

Almond  Peanut  Cashew
Price      10      11       5

In [223]:
total = np.dot(df_butters, df_prices.T)
total

array([[231],
       [ 91],
       [241],
       [183],
       [261]])

In [190]:
df_total = pd.DataFrame(
    data=total,
    columns=['Total'],
    index=None
)
df_total

Total
0    231
1     91
2    241
3    183
4    261

In [245]:
total.reshape((5, 1))
df_b_total = df_butters.copy()
pd.DataFrame.insert(self=df_b_total, loc=np.size(df_butters, axis=1), column='Total', value=total)

In [246]:
df_butters

Almond  Peanut  Cashew
Mon         5      16       1
Tues        5       1       6
Wed         3      16       7
Thurs       9       8       1
Fri         9      11      10

In [247]:
df_b_total

Almond  Peanut  Cashew  Total
Mon         5      16       1    231
Tues        5       1       6     91
Wed         3      16       7    241
Thurs       9       8       1    183
Fri         9      11      10    261

### Importing Images

<img src="./data/images/panda.png" />

In [1]:
from matplotlib.image import imread

In [2]:
panda = imread('./data/images/panda.png', format='png')
panda

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0

In [260]:
panda.size, panda.shape, panda.ndim

(24465000, (2330, 3500, 3), 3)

In [273]:
panda[0][0]

array([0.05490196, 0.10588235, 0.06666667], dtype=float32)